# Generated by Django 4.1.7 on 2023-02-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='card_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('card_cvv', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('card_balance', models.IntegerField(default=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Comment', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField()),
                ('Role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=10)),
                ('Status', models.CharField(choices=[('0', 'INACTIVE'), ('1', 'ACTIVE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=25)),
                ('Pro_image', models.ImageField(upload_to='photos')),
                ('Pro_description', models.TextField()),
                ('Pro_price', models.IntegerField()),
                ('Pro_Cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
                ('Product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='product_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_subcategory_name', models.CharField(max_length=50)),
                ('Product_cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='product_stock_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Updated_time', models.DateTimeField(auto_now=True)),
                ('Pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=35)),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('placed', 'PLACED')], max_length=50)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
            ],
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Pro_Subcat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.product_subcategory'),
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Price', models.IntegerField(default=100)),
                ('Quantity', models.IntegerField()),
                ('Final_price', models.IntegerField()),
                ('Order_id', models.IntegerField(default=0)),
                ('Order_status', models.IntegerField(default=0)),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
                ('Product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='FEEDBACK_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATINGS', models.CharField(max_length=300)),
                ('COMMENT', models.CharField(default='', max_length=300)),
                ('L_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
            ],
        ),
        migrations.CreateModel(
            name='customer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=128)),
                ('dp', models.ImageField(default='mydp.jpeg', upload_to='photos')),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.area')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.city')),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='City_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.city'),
        ),
        migrations.AddField(
            model_name='area',
            name='STATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.state'),
        ),
    ]
