# Generated by Django 4.1 on 2023-02-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_type', models.CharField(max_length=300)),
                ('bottle_image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='customized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iodo.login')),
            ],
        ),
    ]
